class Song:
    def __init__(self, title, artist, genre, duration="0.00", file_path="", image_path=""):
        self.title = title
        self.artist = artist
        self.genre = genre
        self.duration = duration
        self.file_path = file_path
        self.image_path = image_path


SONGS = [
    Song("Nzaza",
         "Asake",
         "Afrobeats",
         "3:03",
         "logic/new resource/nzaza.mp3",
         "logic/pictures/asake.jpg"),
    
    Song("Nakei Nairobi",
         "Mbilia Bel",
         "Afropop",
         "8.38",
         "logic/new resource/Nakei Nairobi - Mbilia Bel.mp3",
         "logic/pictures/nakei nairobi.jpg"),
    
    Song("Kigeugeu",
         "jaguar",
         "Afropop",
         "3.59",
         "logic/new resource/Jaguar- Kigeugeu (Official Ogopa Video ).mp4 - OGOPA DEEJAYS.mp3",
         "logic/pictures/kigeugeu.jpg"),
    
    Song("SICK",
         "Toxic Lyricali",
         "Hip Hop",
         "3.16",
         "logic/new resource/Toxic Lyrikali - SICK (Official Music Video) - Toxic Lyrikali.mp3",
         "logic/pictures/sick.jpg"),
    
    
    Song("Isabella",
         "Sauti Sol",
         "Love Song",
         "4.01",
         "logic/new resource/Sauti Sol - Isabella (Official Music Video) SMS [Skiza 1066769] to 811 - Sauti Sol.mp3",
         "logic/pictures/isabella.jpg"),
    
    Song("Tujiangalie",
         "Sauti Sol",
         "Afropop",
         "4.01",
         "logic/new resource/Sauti Sol - Tujiangalie ft Nyashinski (Official Lyric Video) SMS [Skiza 1051931] to 811 - Sauti Sol.mp3",
         "logic/pictures/tujiangalie.webp"),
    
    Song("Elevate",
         "Nemzz",
         "UK hip hop",
         "2.25",
         "logic/new resource/Nemzzz - Elevate [Music Video]  GRM Daily - GRM Daily.mp3",
         "logic/pictures/nemzz.jpg"),
    
    Song("Tropical",
         "SL",
         "UK hip hop",
         "3.23",
         "logic/new resource/SL - Tropical (Music Video)  MixtapeMadness - Mixtape Madness.mp3",
         "logic/pictures/sl tropical.jpg"),
    
    Song("Me & U",
         "Tems",
         "Love Song",
         "3.23",
         "logic/new resource/Tems - Me & U (Official Video) - TemsVEVO.mp3",
         "logic/pictures/me and u.jpg"),
    
     Song("Pink + White",
         "Frank Ocean",
         "Love Song",
         "3.04",
         "logic/new resource/Pink + White - Frank Ocean.mp3",
         "logic/pictures/frank ocean.jpg"),
     
     Song("Espresso",
         "Sabrina Carpenter",
         "Love Song",
         "3.20",
         "logic/new resource/Sabrina Carpenter - Espresso - SabrinaCarpenterVEVO.mp3",
         "logic/pictures/Espresso.jpg"),
     
     Song("Yebba's Heartbreak",
         "Drake",
         "Love Song",
         "2.14",
         "logic/new resource/Drake - Yebba’s Heartbreak (Audio) - DrakeVEVO.mp3",
         "logic/pictures/yebbas heartbreak.jpg"),
    
    Song("RAMENEZ LA COUPE A LA MAISON",
         "VEGEDREAM",
         "french",
         "4.17",
         "logic/new resource/VEGEDREAM - RAMENEZ LA COUPE A LA MAISON - LARUCHE MUSIC.mp3",
         "logic/pictures/pogba.jpg"),
    
    
    Song("Blackbirds",
         "Lancey Foux",
         "Hip Hop",
         "3:12",
         "logic/new resource/Blackbirds.mp3",
         "logic/pictures/lancey-foux.jpg"),
    
    Song("Face The Flame",
         "Yeat ft. YoungBoy Never Broke Again & Grimes",
         "Hip Hop",
         "2:50",
         "logic/new resource/Face The Flamë (feat. YoungBoy Never Broke Again & Grimes).mp3",
         "logic/pictures/yeat.jpg"),
    
    Song("Ensalada",
         "Freddie Gibbs & The Alchemist ft. Anderson .Paak",
         "Hip Hop",
         "3:20",
         "logic/new resource/Freddie Gibbs & The Alchemist - Ensalada (feat. Anderson .Paak) (Official Visualizer).mp3",
         "logic/pictures/freddie-gibbs.jpg"),
    
    Song("Good Flirts",
         "Baby Keem ft. Kendrick Lamar & Momo Boyd",
         "Hip Hop",
         "3:40",
         "logic/new resource/Baby Keem - Good Flirts (Official Video) ft. Kendrick Lamar, Momo Boyd.mp3",
         "logic/pictures/baby-keem.jpg"),
    
    Song("Bazooka",
         "Miami XO",
         "Hip Hop",
         "2:15",
         "logic/new resource/Miami XO - Bazooka [p.slxwly].mp3",
         "logic/pictures/bazooka.jpg"),
    
    Song("You're the Best",
         "Joe Esposito",
         "Rock",
         "2:59",
         "logic/new resource/You're The Best.mp3",
         "logic/pictures/joe-esposito.jpg"),
    
    Song("Chicago",
         "Michael Jackson",
         "Pop",
         "4:05",
         "logic/new resource/Michael Jackson - Chicago (Official Audio).mp3",
         "logic/pictures/micheal-jackson.jpg"),
    
    Song("One Dance",
         "Drake ft. Wizkid & Kyla",
         "Afrobeats",
         "2:54",
         "logic/new resource/Drake - One Dance (Lyrics) ft. Wizkid & Kyla.mp3",
         "logic/pictures/drake.jpg"),
    
    Song("Ex-Factor",
         "Lauryn Hill",
         "R&B",
         "5:26",
         "logic/new resource/Lauryn Hill - Ex-Factor (Video).mp3",
         "logic/pictures/lauryn-hill.jpg"),
    
    Song("Fountains",
         "Drake ft. Tems",
         "Afrobeats",
         "3:12",
         "logic/new resource/Drake - Fountains (Audio) ft. Tems.mp3",
         "logic/pictures/drake.jpg"),
    
    Song("Glamorous",
         "Fergie ft. Ludacris",
         "Pop",
         "4:03",
         "logic/new resource/Fergie - Glamorous ft. Ludacris.mp3",
         "logic/pictures/fergie.jpg"),

    Song("Gin and Juice",
         "Snoop Dogg",
         "Hip Hop",
         "3:31",
         "logic/new resource/Snoop Dogg - Gin And Juice.mp3",
         "logic/pictures/snoop-dogg.jpg"),

    Song("Hips Don't Lie",
         "Shakira ft. Wyclef Jean",
         "Pop",
         "3:38",
         "logic/new resource/Shakira - Hips Don't Lie (featuring Wyclef Jean) (Official 4K Video) ft. Wyclef Jean.mp3",
         "logic/pictures/shakira.jpg"),

    Song("Get Lucky",
         "Daft Punk ft. Pharrell Williams & Nile Rodgers",
         "Pop",
         "4:08",
         "logic/new resource/Daft Punk - Get Lucky (Official Audio) ft. Pharrell Williams, Nile Rodgers.mp3",
         "logic/pictures/pharell-williams.jpg"),

    Song("No One",
         "Alicia Keys",
         "R&B",
         "4:13",
         "logic/new resource/Alicia Keys - No One (Official Music Video).mp3",
         "logic/pictures/alicia-keys.jpg"),

    Song("Sky",
         "Playboi Carti",
         "Hip Hop",
         "2:48",
         "logic/new resource/Playboi Carti - Sky (Official Audio).mp3",
         "logic/pictures/playboi-carti.jpg"),

    Song("Last Friday Night (T.G.I.F.)",
         "Katy Perry",
         "Pop",
         "3:50",
         "logic/new resource/Katy Perry - Last Friday Night (T.G.I.F.) [Lyrics].mp3",
         "logic/pictures/katy-perry.jpg"),

    Song("Umbrella",
         "Rihanna ft. JAY-Z",
         "Pop",
         "4:35",
         "logic/new resource/Rihanna - Umbrella (Orange Version) (Official Music Video) ft. JAY-Z.mp3",
         "logic/pictures/rihanna.jpg"),

    Song("Waterfalls",
         "TLC",
         "R&B",
         "4:39",
         "logic/new resource/TLC - Waterfalls (Official HD Video).mp3",
         "logic/pictures/tlc.jpg"),

    Song("Magnolia",
         "Playboi Carti",
         "Hip Hop",
         "3:01",
         "logic/new resource/Playboi Carti - Magnolia (Official Video).mp3",
         "logic/pictures/playboi-carti.jpg"),

    Song("Firework",
         "Katy Perry",
         "Pop",
         "3:50",
         "logic/new resource/Katy Perry - Firework (Official Music Video).mp3",
         "logic/pictures/katty-perry.jpg"),

    Song("Diamonds",
         "Rihanna",
         "Pop",
         "3:45",
         "logic/new resource/Rihanna - Diamonds.mp3",
         "logic/pictures/rihanna.jpg"),

    Song("No Scrubs",
         "TLC",
         "R&B",
         "3:36",
         "logic/new resource/TLC - No Scrubs (Official HD Video).mp3",
         "logic/pictures/tlc.jpg"),

    Song("Billie Jean",
         "Michael Jackson",
         "Pop",
         "4:54",
         "logic/new resource/Michael Jackson - Billie Jean (Official Audio).mp3",
         "logic/pictures/micheal-jackson.jpg"),

    Song("God's Plan",
         "Drake",
         "Hip Hop",
         "3:18",
         "logic/new resource/Drake - God's Plan.mp3",
         "logic/pictures/drake.jpg"),

    Song("Terminator",
         "Asake",
         "Afrobeats",
         "3:25",
         "logic/new resource/Asake - Terminator (Official Video).mp3",
         "logic/pictures/asake.jpg"),

    Song("Empire State of Mind",
         "JAY-Z ft. Alicia Keys",
         "Hip Hop",
         "4:37",
         "logic/new resource/JAY-Z - Empire State Of Mind ft. Alicia Keys.mp3",
         "logic/pictures/alicia-keys.jpg"),
    Song(
         "Through the Wire",
         "Kanye West",
         "Hip Hop",
         "3.41",
          "logic/new resource/19.Through The Wire.mp3",
         "logic/pictures/college dropout.jpg"
         
    ),

    Song("Waka Waka (This Time for Africa)",
         "Shakira ft. Freshlyground",
         "Pop",
         "3:22",
         "logic/new resource/Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song).mp3",
         "logic/pictures/shakira.jpg"),

    Song("Hot N Cold",
         "Katy Perry",
         "Pop",
         "3:40",
         "logic/new resource/Katy Perry - Hot N Cold (Official Music Video).mp3",
         "logic/pictures/katy-perry.jpg"),

    Song("Don't Stop the Music",
         "Rihanna",
         "Pop",
         "4:27",
         "logic/new resource/Rihanna - Don't Stop The Music.mp3",
         "logic/pictures/rihanna.jpg"),

    Song("Stronger",
         "Kanye West",
         "Hip Hop",
         "5:12",
         "logic/new resource/Kanye West - Stronger.mp3",
         "logic/pictures/graduation.jpg"),

    Song("Roses",
         "Kanye West",
         "Hip Hop",
         "4:06",
         "logic/new resource/Roses.mp3",
         "logic/pictures/kanye west.jpg"),

    Song("All of the Lights",
         "Kanye West ft. Rihanna & Kid Cudi",
         "Hip Hop",
         "4:59",
         "logic/new resource/Kanye West - All Of The Lights ft. Rihanna, Kid Cudi.mp3",
         "logic/pictures/cover.jpg"),

    Song("Natural High",
         "Freddie Gibbs",
         "Hip Hop",
         "3:31",
         "logic/new resource/Natural High (Even Higher Learning).mp3",
         "logic/pictures/freddie-gibbs.jpg"),

    Song("SDP Interlude",
         "Travis Scott",
         "Hip Hop",
         "3:11",
         "logic/new resource/Travis Scott - sdp interlude (Extended).mp3",
         "logic/pictures/travis scott.jpg"),

    Song("Antidote",
         "Travis Scott",
         "Hip Hop",
         "4:22",
         "logic/new resource/Travis Scott - Antidote.mp3",
         "logic/pictures/travis scott.jpg"),

    Song("Lights",
         "Ellie Goulding",
         "Pop",
         "3:30",
         "logic/new resource/Ellie Goulding - Lights (Official Video).mp3",
         "logic/pictures/ellie goulding.jpg"),

    Song("Lush Life",
         "Zara Larsson",
         "Pop",
         "3:21",
         "logic/new resource/Zara Larsson - Lush Life (Official Video).mp3",
         "logic/pictures/zara larsson.jpg"),

    Song("No Role Modelz",
         "J. Cole",
         "Hip Hop",
         "4:52",
         "logic/new resource/No Role Modelz.mp3",
         "logic/pictures/j cole.jpg")
]