def library():
    songs = [
        {
            "index": 1,
            "song_name": "Nzaza",
            "artist": "Asake",
            "image": "/logic/pictures/asake.jpg",
            "audio": "/logic/new resource/Asake - Nzaza (Official Visualizer).mp3",
            "duration": "3:03",
        },
        {
            "index": 2,
            "song_name": "Blackbirds",
            "artist": "Lancey Foux",
            "image": "/logic/pictures/lancey-foux.jpg",
            "audio": "/logic/new resource/Blackbirds.mp3",
            "duration": "3:12",
        },
        {
            "index": 3,
            "song_name": "Face The Flame",
            "artist": "Yeat ft. YoungBoy Never Broke Again & Grimes",
            "image": "/logic/pictures/yeat.jpg",
            "audio": "/logic/new resource/Face The Flamë (feat. YoungBoy Never Broke Again & Grimes).mp3",
            "duration": "2:50",
        },
        {
            "index": 4,
            "song_name": "Ensalada",
            "artist": "Freddie Gibbs & The Alchemist ft. Anderson .Paak",
            "image": "/logic/pictures/freddie.jpg",
            "audio": "/logic/new resource/Freddie Gibbs & The Alchemist - Ensalada (feat. Anderson .Paak) (Official Visualizer).mp3",
            "duration": "3:20",
        },
        {
            "index": 5,
            "song_name": "Good Flirts",
            "artist": "Baby Keem ft. Kendrick Lamar & Momo Boyd",
            "image": "/logic/pictures/baby-keem.jpg",
            "audio": "/logic/new resource/Baby Keem - Good Flirts (Official Video) ft. Kendrick Lamar, Momo Boyd.mp3",
            "duration": "3:40",
        },
        {
            "index": 6,
            "song_name": "Bazooka",
            "artist": "Miami XO",
            "image": "/logic/pictures/bazooka.jpg",
            "audio": "/logic/new resource/Miami XO - Bazooka [p.slxwly].mp3",
            "duration": "2:15",
        },
        {
            "index": 7,
            "song_name": "You're the Best",
            "artist": "Joe Esposito",
            "image": "/logic/pictures/joe-esposito.jpg",
            "audio": "/logic/new resource/You're The Best.mp3",
            "duration": "2:59",
        },
        {
            "index": 8,
            "song_name": "Chicago",
            "artist": "Michael Jackson",
            "image": "/logic/pictures/michael-jackson.jpg",
            "audio": "/logic/new resource/Michael Jackson - Chicago (Official Audio).mp3",
            "duration": "4:05",
        },
        {
            "index": 9,
            "song_name": "One Dance",
            "artist": "Drake ft. Wizkid & Kyla",
            "image": "/logic/pictures/drake.jpg",
            "audio": "/logic/new resource/Drake - One Dance (Lyrics) ft. Wizkid & Kyla.mp3",
            "duration": "2:54",
        },
        {
            "index": 10,
            "song_name": "Ex-Factor",
            "artist": "Lauryn Hill",
            "image": "/logic/pictures/lauryn-hill.jpg",
            "audio": "/logic/new resource/Lauryn Hill - Ex-Factor (Video).mp3",
            "duration": "5:26",
        },
        {
            "index": 11,
            "song_name": "Fountains",
            "artist": "Drake ft. Tems",
            "image": "/logic/pictures/drake.jpg",
            "audio": "/logic/new resource/Drake - Fountains (Audio) ft. Tems.mp3",
            "duration": "3:12",
        },
        {
            "index": 12,
            "song_name": "Glamorous",
            "artist": "Fergie ft. Ludacris",
            "image": "/logic/pictures/fergie.jpg",
            "audio": "/logic/new resource/Fergie - Glamorous ft. Ludacris.mp3",
            "duration": "4:03",
        },
        {
            "index": 13,
            "song_name": "Gin and Juice",
            "artist": "Snoop Dogg",
            "image": "/logic/pictures/snoop-dogg.jpg",
            "audio": "/logic/new resource/Snoop Dogg - Gin And Juice.mp3",
            "duration": "3:31",
        },
        {
            "index": 14,
            "song_name": "Hips Don't Lie",
            "artist": "Shakira ft. Wyclef Jean",
            "image": "/logic/pictures/shakira.jpg",
            "audio": "/logic/new resource/Shakira - Hips Don't Lie (featuring Wyclef Jean) (Official 4K Video) ft. Wyclef Jean.mp3",
            "duration": "3:38",
        },
        {
            "index": 15,
            "song_name": "Get Lucky",
            "artist": "Daft Punk ft. Pharrell Williams & Nile Rodgers",
            "image": "/logic/pictures/pharell-williams.jpg",
            "audio": "/logic/new resource/Daft Punk - Get Lucky (Official Audio) ft. Pharrell Williams, Nile Rodgers.mp3",
            "duration": "4:08",
        },
        {
            "index": 16,
            "song_name": "No One",
            "artist": "Alicia Keys",
            "image": "/logic/pictures/alicia-keys.jpg",
            "audio": "/logic/new resource/Alicia Keys - No One (Official Music Video).mp3",
            "duration": "4:13",
        },
        {
            "index": 17,
            "song_name": "Sky",
            "artist": "Playboi Carti",
            "image": "/logic/pictures/playboi-carti.jpg",
            "audio": "/logic/new resource/Playboi Carti - Sky (Official Audio).mp3",
            "duration": "2:48",
        },
        {
            "index": 18,
            "song_name": "Last Friday Night (T.G.I.F.)",
            "artist": "Katy Perry",
            "image": "/logic/pictures/katy-perry.jpg",
            "audio": "/logic/new resource/Katy Perry - Last Friday Night (T.G.I.F.) [Lyrics].mp3",
            "duration": "3:50",
        },
        {
            "index": 19,
            "song_name": "Umbrella",
            "artist": "Rihanna ft. JAY-Z",
            "image": "/logic/pictures/rihanna.jpg",
            "audio": "/logic/new resource/Rihanna - Umbrella (Orange Version) (Official Music Video) ft. JAY-Z.mp3",
            "duration": "4:35",
        },
        {
            "index": 20,
            "song_name": "Waterfalls",
            "artist": "TLC",
            "image": "/logic/pictures/tlc.jpg",
            "audio": "/logic/new resource/TLC - Waterfalls (Official HD Video).mp3",
            "duration": "4:39",
        },      
        {
            "index": 21,
            "song_name": "Magnolia",
            "artist": "Playboi Carti",
            "image": "/logic/pictures/playboi-carti.jpg",
            "audio": "/logic/new resource/Playboi Carti - Magnolia (Official Video).mp3",
            "duration": "3:01",
        },
        {
            "index": 22,
            "song_name": "Firework",
            "artist": "Katy Perry",
            "image": "/logic/pictures/katy-perry.jpg",
            "audio": "/logic/new resource/Katy Perry - Firework (Official Music Video).mp3",
            "duration": "3:50",
        },
        {
            "index": 23,
            "song_name": "Diamonds",
            "artist": "Rihanna",
            "image": "/logic/pictures/rihanna.jpg",
            "audio": "/logic/new resource/Rihanna - Diamonds.mp3",
            "duration": "3:45",
        },
        {
            "index": 24,
            "song_name": "No Scrubs",
            "artist": "TLC",
            "image": "/logic/pictures/tlc.jpg",
            "audio": "/logic/new resource/TLC - No Scrubs (Official HD Video).mp3",
            "duration": "3:36",
        },
                {
            "index": 25,
            "song_name": "Billie Jean",
            "artist": "Michael Jackson",
            "image": "/logic/pictures/michael-jackson.jpg",
            "audio": "/logic/new resource/Michael Jackson - Billie Jean (Official Audio).mp3",
            "duration": "4:54",
        },
        {
            "index": 26,
            "song_name": "God's Plan",
            "artist": "Drake",
            "image": "/logic/pictures/drake.jpg",
            "audio": "/logic/new resource/Drake - God's Plan.mp3",
            "duration": "3:18",
        },
                {
            "index": 27,
            "song_name": "Terminator",
            "artist": "Asake",
            "image": "/logic/pictures/asake.jpg",
            "audio": "/logic/new resource/Asake - Terminator (Official Video).mp3",
            "duration": "3:25",
        },
        {
            "index": 28,
            "song_name": "Empire State of Mind",
            "artist": "JAY-Z ft. Alicia Keys",
            "image": "/logic/pictures/alicia-keys.jpg",
            "audio": "/logic/new resource/JAY-Z - Empire State Of Mind ft. Alicia Keys.mp3",
            "duration": "4:37",
        },
        {
            "index": 29,
            "song_name": "Waka Waka (This Time for Africa)",
            "artist": "Shakira ft. Freshlyground",
            "image": "/logic/pictures/shakira.jpg",
            "audio": "/logic/new resource/Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song).mp3",
            "duration": "3:22",
        },
        {
            "index": 30,
            "song_name": "Hot N Cold",
            "artist": "Katy Perry",
            "image": "/logic/pictures/katy-perry.jpg",
            "audio": "/logic/new resource/Katy Perry - Hot N Cold (Official Music Video).mp3",
            "duration": "3:40",
        },
        {
            "index": 31,
            "song_name": "Don't Stop the Music",
            "artist": "Rihanna",
            "image": "/logic/pictures/rihanna.jpg",
            "audio": "/logic/new resource/Rihanna - Don't Stop The Music.mp3",
            "duration": "4:27",
        },
        {
            "index": 32,
            "song_name": "Stronger",
            "artist": "Kanye West",
            "image": "/logic/pictures/kanye-west.jpg",
            "audio": "/logic/new resource/Kanye West - Stronger.mp3",
            "duration": "5:12",
        },
        {
            "index": 33,
            "song_name": "Roses",
            "artist": "Kanye West",
            "image": "/logic/pictures/kanye-west.jpg",
            "audio": "/logic/new resource/Roses.mp3",
            "duration": "4:06",
        },
        {
            "index": 34,
            "song_name": "All of the Lights",
            "artist": "Kanye West ft. Rihanna & Kid Cudi",
            "image": "/logic/pictures/kanye-west.jpg",
            "audio": "/logic/new resource/Kanye West - All Of The Lights ft. Rihanna, Kid Cudi.mp3",
            "duration": "4:59",
        },
        {
            "index": 35,
            "song_name": "Natural High",
            "artist": "Freddie Gibbs",
            "image": "/logic/pictures/freddie.jpg",
            "audio": "/logic/new resource/Natural High (Even Higher Learning).mp3",
            "duration": "3:31",
        },
        {
            "index": 36,
            "song_name": "SDP Interlude",
            "artist": "Travis Scott",
            "image": "/logic/pictures/travis-scott.jpg",
            "audio": "/logic/new resource/Travis Scott - sdp interlude (Extended).mp3",
            "duration": "3:11",
        },
        {
            "index": 37,
            "song_name": "Antidote",
            "artist": "Travis Scott",
            "image": "/logic/pictures/travis-scott.jpg",
            "audio": "/logic/new resource/Travis Scott - Antidote.mp3",
            "duration": "4:22",
        },
        {
            "index": 38,
            "song_name": "Lights",
            "artist": "Ellie Goulding",
            "image": "/logic/pictures/ellie-goulding.jpg",
            "audio": "/logic/new resource/Ellie Goulding - Lights (Official Video).mp3",
            "duration": "3:30",
        },
        {
            "index": 39,
            "song_name": "Lush Life",
            "artist": "Zara Larsson",
            "image": "/logic/pictures/zara-larsson.jpg",
            "audio": "/logic/new resource/Zara Larsson - Lush Life (Official Video).mp3",
            "duration": "3:21",
        },
        {
            "index": 40,
            "song_name": "No Role Modelz",
            "artist": "J. Cole",
            "image": "/logic/pictures/j-cole.jpg",
            "audio": "/logic/new resource/No Role Modelz.mp3",
            "duration": "4:52",
        },
    ]
    return songs
